export const SNACKS_MENU_REQUEST = 'SNACKS_MENU_REQUEST';
export const SNACKS_MENU_SUCCESS = 'SNACKS_MENU_SUCCESS';
export const SNACKS_MENU_FAIL = 'SNACKS_MENU_FAIL';

export const APPETIZER_MENU_REQUEST = 'APPETIZER_MENU_REQUEST';
export const APPETIZER_MENU_SUCCESS = 'APPETIZER_MENU_SUCCESS';
export const APPETIZER_MENU_FAIL = 'APPETIZER_MENU_FAIL';

export const MAINMENU_MENU_REQUEST = 'MAINMENU_MENU_REQUEST';
export const MAINMENU_MENU_SUCCESS = 'MAINMENU_MENU_SUCCESS';
export const MAINMENU_MENU_FAIL = 'MAINMENU_MENU_FAIL';

export const PIZZA_MENU_REQUEST = 'PIZZA_MENU_REQUEST';
export const PIZZA_MENU_SUCCESS = 'PIZZA_MENU_SUCCESS';
export const PIZZA_MENU_FAIL = 'PIZZA_MENU_FAIL';

export const DESSERT_MENU_REQUEST = 'DESSERT_MENU_REQUEST';
export const DESSERT_MENU_SUCCESS = 'DESSERT_MENU_SUCCESS';
export const DESSERT_MENU_FAIL = 'DESSERT_MENU_FAIL';

export const BURGER_MENU_REQUEST = 'BURGER_MENU_REQUEST';
export const BURGER_MENU_SUCCESS = 'BURGER_MENU_SUCCESS';
export const BURGER_MENU_FAIL = 'BURGER_MENU_FAIL';

export const SEAFOOD_MENU_REQUEST = 'SEAFOOD_MENU_REQUEST';
export const SEAFOOD_MENU_SUCCESS = 'SEAFOOD_MENU_SUCCESS';
export const SEAFOOD_MENU_FAIL = 'SEAFOOD_MENU_FAIL';

export const COCKTAIL_MENU_REQUEST = 'COCKTAIL_MENU_REQUEST';
export const COCKTAIL_MENU_SUCCESS = 'COCKTAIL_MENU_SUCCESS';
export const COCKTAIL_MENU_FAIL = 'COCKTAIL_MENU_FAIL';

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL';

// for creating new menu items in frontend
export const APPETIZER_CREATE_REQUEST = 'APPETIZER_CREATE_REQUEST';
export const APPETIZER_CREATE_SUCCESS = 'APPETIZER_CREATE_SUCCESS';
export const APPETIZER_CREATE_FAIL = 'APPETIZER_CREATE_FAIL';
export const APPETIZER_CREATE_RESET = 'APPETIZER_CREATE_RESET';

export const BURGER_CREATE_REQUEST = 'BURGER_CREATE_REQUEST';
export const BURGER_CREATE_SUCCESS = 'BURGER_CREATE_SUCCESS';
export const BURGER_CREATE_FAIL = 'BURGER_CREATE_FAIL';
export const BURGER_CREATE_RESET = 'BURGER_CREATE_RESET';

export const COCKTAIL_CREATE_REQUEST = 'COCKTAIL_CREATE_REQUEST';
export const COCKTAIL_CREATE_SUCCESS = 'COCKTAIL_CREATE_SUCCESS';
export const COCKTAIL_CREATE_FAIL = 'COCKTAIL_CREATE_FAIL';
export const COCKTAIL_CREATE_RESET = 'COCKTAIL_CREATE_RESET';

export const DESSERT_CREATE_REQUEST = 'DESSERT_CREATE_REQUEST';
export const DESSERT_CREATE_SUCCESS = 'DESSERT_CREATE_SUCCESS';
export const DESSERT_CREATE_FAIL = 'DESSERT_CREATE_FAIL';
export const DESSERT_CREATE_RESET = 'DESSERT_CREATE_RESET';

export const MAINMENU_CREATE_REQUEST = 'MAINMENU_CREATE_REQUEST';
export const MAINMENU_CREATE_SUCCESS = 'MAINMENU_CREATE_SUCCESS';
export const MAINMENU_CREATE_FAIL = 'MAINMENU_CREATE_FAIL';
export const MAINMENU_CREATE_RESET = 'MAINMENU_CREATE_RESET';

export const PIZZA_CREATE_REQUEST = 'PIZZA_CREATE_REQUEST';
export const PIZZA_CREATE_SUCCESS = 'PIZZA_CREATE_SUCCESS';
export const PIZZA_CREATE_FAIL = 'PIZZA_CREATE_FAIL';
export const PIZZA_CREATE_RESET = 'PIZZA_CREATE_RESET';

export const SEAFOOD_CREATE_REQUEST = 'SEAFOOD_CREATE_REQUEST';
export const SEAFOOD_CREATE_SUCCESS = 'SEAFOOD_CREATE_SUCCESS';
export const SEAFOOD_CREATE_FAIL = 'SEAFOOD_CREATE_FAIL';
export const SEAFOOD_CREATE_RESET = 'SEAFOOD_CREATE_RESET';

export const SNACK_CREATE_REQUEST = 'SNACK_CREATE_REQUEST';
export const SNACK_CREATE_SUCCESS = 'SNACK_CREATE_SUCCESS';
export const SNACK_CREATE_FAIL = 'SNACK_CREATE_FAIL';
export const SNACK_CREATE_RESET = 'SNACK_CREATE_RESET';


export const PRODUCT_UPDATE_REQUEST = 'PRODUCT_UPDATE_REQUEST';
export const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS';
export const PRODUCT_UPDATE_FAIL = 'PRODUCT_UPDATE_FAIL';
export const PRODUCT_UPDATE_RESET = 'PRODUCT_UPDATE_RESET';

export const MENUITEM_DELETE_REQUEST = 'MENUITEM_DELETE_REQUEST';
export const MENUITEM_DELETE_SUCCESS = 'MENUITEM_DELETE_SUCCESS';
export const MENUITEM_DELETE_FAIL = 'APPETIZER_DELETE_FAIL';
export const MENUITEM_DELETE_RESET = 'APPETIZER_DELETE_RESET';