export const HOMEMENU_CARD_REQUEST = 'HOMEMENU_CARD_REQUEST';
export const HOMEMENU_CARD_SUCCESS = 'HOMEMENU_CARD_SUCCESS';
export const HOMEMENU_CARD_FAIL = 'HOMEMENU_CARD_FAIL';

export const MENUPAGE_CARD_REQUEST = 'MENUPAGE_CARD_REQUEST';
export const MENUPAGE_CARD_SUCCESS = 'MENUPAGE_CARD_SUCCESS';
export const MENUPAGE_CARD_FAIL = 'MENUPAGE_CARD_FAIL';